package com.sheldera.practicebot.x;

public enum by {
   NONE,
   PLACE_SAFE,
   BREAK_SAFE,
   CREATE_OBSIDIAN_PRESSURE,
   SELF_DAMAGE_UNSAFE_RECOVERY,
   INVALID_NO_BASE,
   INVALID_NO_LOS,
   INVALID_OUT_OF_REACH,
   INVALID_VERTICAL,
   INVALID_NO_RESOURCES,
   INVALID_NO_SPACE,
   INVALID_LOW_DAMAGE,
   INVALID_STALE;
}
